### ISSUE TITLE
"expected struct `css_in_rust::style::Style`, found enum `std::result::Result`"

### ISSUE THREAD

**Issue by nugetchar** [lukidoescode/css-in-rust#9]
When trying to play with the example, I get the following error:

`expected struct 'css_in_rust::style::Style', found enum 'std::result::Result'`

My `Cargo.toml` is as following:

```toml
[dependencies]
log = "0.4"
wasm-logger = "0.2"
wasm-bindgen = "0.2.62"
serde = "1.0"
serde_derive = "1.0"
yew = "0.15"
web-sys = "0.3.39"

[dependencies.css-in-rust]
version = "0.2.2"
features = ["yew_integration", "web_sys", "seed_integration"]
```

And my code is pretty much the same as in the last example: 

```rust
use web_sys::HtmlInputElement;
use yew::prelude::*;
use css_in_rust::*;

pub struct Model {
    link: ComponentLink<Self>,
    node_ref: NodeRef,
    pub style: css_in_rust::Style,
}

pub enum Msg {
    SendMessage,
}

impl Component for Model {
    type Message = Msg;
    type Properties = ();

    // https://doc.rust-lang.org/rust-by-example/trait.html
    fn create(_: Self::Properties, link: ComponentLink<Self>) -> Self {
        let style = match css_in_rust::Style::create(
            String::from("Model"), 
            String::from(
                r#"
                    width: 100%;
                    margin: auto;
                    height: 150px;
                    display: flex;
                    max-width: 700px;
                "#,
            ),
        ) {
           // this is where the compilation fails
            Ok(style) => {style},
            Err(error)  => {
                panic!("An error occured while creating the style {}", error);
            }
        };
        Self {
            link,
            node_ref: NodeRef::default(),
            style
        }
    }


    ...
}

```
